# Site settings
title: Sandy E. Wolf
sub_title: LCSW
email: sandyw@sandywolfpsychotherapy.com
phone_number: 2034885114
phone_number_formatted: 203.488.5114
street_address: 1090 Main Street
city: Branford
locale: CT
zip: 06045
work_org: Sandy E. Wolf, LCSW
work_link: http://www.sandywolf.com
description: Licensed Clinical Social Worker
baseurl: "/sandy-wolf-website" # the subpath of your site, e.g. /blog/
url: "http://somecallmejosh.github.io" # the base hostname & protocol for your site
exclude: [vendor]
sass:
  style: :compressed

# Build settings
markdown: kramdown
permalink: /:title

#Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Sandy Wolf
      category: design
      permalink: /blog/:title/
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
